name: Build the SPFx solution
on:
  push:
    tags:
      - "spfx-v*"
  workflow_dispatch:

permissions:
  contents: write

env:
  NODE_VERSION: '18.x'
  WORKING_DIRECTORY: './spfx-solution'

jobs:
  build-spfx-solution:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Run npm ci
        run: npm ci
      
      - name: Extract version number from git tag name
        if: startsWith(github.ref, 'refs/tags/spfx-v')
        env:
          TAG: ${{ github.ref_name }}
        id: splittag
        run: echo "spfxversion=`echo $TAG | grep -oP '(?<=spfx-v)[\d+?\.]*'`" >> $GITHUB_OUTPUT
        
      - name: Set version in package-solution.json
        if: startsWith(github.ref, 'refs/tags/spfx-v')
        run: jq --arg version "${{ steps.splittag.outputs.spfxversion }}" '.solution.version = $version' config/package-solution.json > tmp.json && mv tmp.json config/package-solution.json

      - name: Bundle & Package
        run: |
          gulp bundle --ship
          gulp package-solution --ship
      
      - uses: actions/upload-artifact@v4
        with:
          name: 'SPFx package'
          path: '${{ env.WORKING_DIRECTORY }}/sharepoint/solution/*.sppkg'
     
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/spfx-v')
        with:
          name: 'SPFx package v${{ steps.splittag.outputs.spfxversion }}'
          files: '${{ env.WORKING_DIRECTORY }}/sharepoint/solution/*.sppkg'
          draft: true
          make_latest: true
