name: Build the SPFx solution
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: '18.x'
  WORKING_DIRECTORY: './spfx-custom-api'

jobs:
  build-spfx-solution:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIRECTORY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Run npm ci
        run: npm ci
      - name: Bundle & Package
        run: |
          gulp bundle --ship
          gulp package-solution --ship
      - uses: actions/upload-artifact@v4
        with:
          name: 'SPFx package'
          path: '${{ env.WORKING_DIRECTORY }}/sharepoint/solution/*.sppkg'
